name: cse6250-project-sleep
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - mne
  - seaborn
  - lightgbm
  - python=3.6
  - pytorch>=1.3.0
  - torchvision
  # - cudatoolkit>=9.2    # mac OS users should comment out this (for CPU only) or build from the source
  - scikit-learn
  - numpy
  - scipy
  - pandas
  - matplotlib==3.1.0
  - nb_conda_kernels
  - pytest
  - pip
  - pip:
      - delayed-assert
